name: FalloutCore
version: '1.0-SNAPSHOT'
main: me.mapacheee.falloutcore.FalloutWinterPlugin
api-version: '1.21'

depend: [PlaceholderAPI, packetevents]

commands:
  faction:
    description: Comandos de facciones
    usage: /faction [create|delete|join|forcejoin|kick|setalias|info]
    aliases: [f]

  radiation:
    description: Comandos del sistema de radiaci칩n
    usage: /radiation [info|setlevel|setheight|check|immunity]
    aliases: [rad]

permissions:
  falloutcore.radiation.immune:
    description: Inmune a la radiaci칩n
    default: op
  falloutcore.radiation.admin:
    description: Permisos de administrador para el sistema de radiaci칩n
    default: op
  falloutcore.faction.admin:
    description: Permisos de administrador para facciones
    default: op
  falloutcore.faction.use:
    description: Permite usar comandos b치sicos de facciones
    default: true
