name: falloutcore
version: '1.0-SNAPSHOT'
main: me.mapacheee.falloutcore.FalloutCore
api-version: '1.21'

depend: [PacketEvents]
softdepend: [PlaceholderAPI]

commands:
  faction:
    description: Comandos de facciones
    usage: /faction [create|delete|join|forcejoin|kick|setalias]
  bomba:
    description: Comandos de bombas
    usage: /bomba [c4|nuclear]

permissions:
  fallout.radiationinmune:
    description: Inmune a la radiación
    default: op
  falloutcore.factions.admin:
    description: Permisos de administrador para facciones
    default: op